version: '4'
services:
  www:
      image: php:apache
      volumes: 
        - "./:/var/www/html" # sync project dir with container web dir
      ports:
        - 80:80
        - 443:443 # for future ssl traffic
  db:
    image: mysql:latest
    environment: 
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # should be in an env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # set to true
    volumes:
      - "./db:/docker-entrypoint-initdb.d" #sync persistent sql files with container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306